version: "2.1"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: eczachly-flink-zookeeper
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: eczachly-flink-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "payment_msg:1:1"
  generator:
    build: generator
    container_name: eczachly-flink-data-generator
    image: generator:1.0
    depends_on:
      - kafka
