version: "3.9"
services:
  jobmanager:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        # If you update the flink version here, be sure to update the docker base image as well
        FLINK_VERSION: "1.16.0"
        PYTHON_VERSION: "3.10"
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: kafka-flink-postgres:latest
    pull_policy: never
    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: jobmanager
    container_name: eczachly-flink-jobmanager
    env_file:
      - flink-env.env
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./:/opt/flink/usrlib
      - ./keys/:/var/private/
      - ./job/:/opt/job/

  taskmanager:
    image: kafka-flink-postgres:latest
    pull_policy: never
    depends_on:
      - jobmanager
    command: taskmanager
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: eczachly-flink-taskmanager
    scale: 1
    volumes:
      - ./:/opt/flink/usrlib
      - ./keys/:/var/private/
      - ./job/:/opt/job/
    env_file:
      - flink-env.env

